appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: nL0McShO9jYNexpQIxgfy5Py7OKVXSaWLMMaiD+hEK6lxjLtWMosBWOWj/+5votPYBlpI89m93onzBy1aRU2aCMCnRg0QQ9FIJlF/0qT4C+Inum/mRKffhawRM9DZwtI3pinAMopVtoxNjkEdc8eUWcSdEwMqG+QdlE3IL3wlaE9E0/CbBwoIM1ylTY7NlQ8MErbi0u31moowmr/1fMCzo5FyiA+lLSUAZkJxu/SZiw8EEAxTxIH94ZM/PMngO9/PPQRo7V2z/wtOBtHMw+Wop2hFgW07vhf9Oj9Mf8ifSdhy8LRbwB2AHgX7zzQLt0m1qWwAzK5rJYyOE/PPpisy9KIuC3QL/T4K1CBpoF1p0IISn57wWbmXn6YS90i09Th/z1KGREhiX1mvoULg36GCcvgc2gP3m7GPwHJO0nF5Ab2VuSk5XFuv1HYnRK0hhik/M/bWlFMgUZTix4jKujOuJP8G6MgO6kUIkMr7jp32aa+ze286E69/exJgSPJ/P/nuFXKiQZ6TfZ/WQ5gobYLIAfvpZ+buBpPzCu0DiAkzSm+yHc1uKCW5fez+1rXhJ7Gva5mTr+mLLjT9J9XFYfB/TtiLMlF1KhsOUkdPXemakgdzinv7wVHGEKKYv8Ds3JWexPAL3awEORO8hO1pdBkVnsR3a62GFk4sLDiq6H6j1A=}
bot:
  automerge: true
